import { GalleryImage } from "./GalleryType";

export const galleryImages: GalleryImage[] = [
    {
        id: 1,
        src: "/images/Gallery/KAZ1.jpg",
        alt: "Gallery Image 1",
        width: 1200,
        height: 800,
    },
    // {
    //     id: 2,
    //     src: "/images/Gallery/KAZ2.jpg",
    //     alt: "Gallery Image 2",
    //     width: 1200,
    //     height: 800,
    // },
    {
        id: 3,
        src: "/images/Gallery/KAZ3.jpg",
        alt: "Gallery Image 3",
        width: 1200,
        height: 800,
    },
    {
        id: 4,
        src: "/images/Gallery/KAZ4.jpg",
        alt: "Gallery Image 4",
        width: 1200,
        height: 800,
    },
    {
        id: 5,
        src: "/images/Gallery/KAZ5.jpg",
        alt: "Gallery Image 5",
        width: 1200,
        height: 800,
    },
    {
        id: 6,
        src: "/images/Gallery/KAZ6.jpg",
        alt: "Gallery Image 6",
        width: 1200,
        height: 800,
    },
    {
        id: 7,
        src: "/images/Gallery/KAZ7.jpg",
        alt: "Gallery Image 7",
        width: 1200,
        height: 800,
    },
    {
        id: 8,
        src: "/images/Gallery/KAZ8.jpg",
        alt: "Gallery Image 8",
        width: 1200,
        height: 800,
    },
    {
        id: 9,
        src: "/images/Gallery/KAZ9.jpg",
        alt: "Gallery Image 9",
        width: 1200,
        height: 800,
    },
    {
        id: 10,
        src: "/images/Gallery/KAZ10.jpg",
        alt: "Gallery Image 10",
        width: 1200,
        height: 800,
    },
    {
        id: 11,
        src: "/images/Gallery/KAZ11.jpg",
        alt: "Gallery Image 11",
        width: 1200,
        height: 800,
    },
    // {
    //     id: 12,
    //     src: "/images/Gallery/KAZ12.jpg",
    //     alt: "Gallery Image 12",
    //     width: 1200,
    //     height: 800,
    // },
    {
        id: 13,
        src: "/images/Gallery/KAZ13.jpg",
        alt: "Gallery Image 13",
        width: 1200,
        height: 800,
    },
    {
        id: 14,
        src: "/images/Gallery/KAZ14.jpg",
        alt: "Gallery Image 14",
        width: 1200,
        height: 800,
    },
    {
        id: 15,
        src: "/images/Gallery/KAZ15.jpg",
        alt: "Gallery Image 15",
        width: 1200,
        height: 800,
    },
    {
        id: 16,
        src: "/images/Gallery/KAZ16.jpg",
        alt: "Gallery Image 16",
        width: 1200,
        height: 800,
    },
];